# Generated by Django 2.2.5 on 2019-09-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamiAPP', '0002_auto_20190915_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersub',
            name='where',
            field=models.CharField(blank=True, default='anon', max_length=100),
        ),
    ]
