# Generated by Django 2.2.5 on 2019-09-29 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tamiAPP', '0003_auto_20190929_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersub',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
