# Generated by Django 2.2.5 on 2019-10-05 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamiAPP', '0005_auto_20191001_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersub',
            name='rank',
        ),
    ]
